name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt update && sudo apt install -y cmake build-essential

      - name: Configure project with CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run client test
        run: |
            ./build/client_test || echo "Expected fail -> Server Not running"
