name: Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt update && sudo apt install -y cmake build-essential

      - name: Configure project with CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Start server
        run:  ./build/bin/Hydra & sleep 1

      - name: Run client test
        run: |
            ./build/bin/client_test
